export const API_KEY = '8fb4b0a5aef51d77af329bffc715e247';
export const SEARCH_REQUESTED = 'SEARCH_REQUESTED';
export const SEARCH_REQUESTED_FAIL = 'SEARCH_REQUESTED_FAIL';
export const SERIE_DETAILS_REQUESTED = 'SERIE_DETAILS_REQUESTED';
export const SEASON_DETAILS_REQUESTED = 'SEASON_DETAILS_REQUESTED';